# Generated by Django 5.1.2 on 2024-10-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_rename_categoria_cliente_categoria_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ventas',
            new_name='Venta',
        ),
    ]
