# Generated by Django 5.1.2 on 2024-10-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_rename_ventas_venta'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='id_product',
            new_name='id_producto',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='id_user',
            new_name='id_usuario',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='id_sale',
            new_name='id_venta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
    ]
