# Generated by Django 5.1.2 on 2024-10-20 03:29

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_alter_usuario_managers_rename_date_venta_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
