# Generated by Django 5.1.2 on 2024-10-20 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_alter_usuario_managers_remove_usuario_contrasena_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
    ]
