# Generated by Django 5.1.2 on 2024-10-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0012_remove_usuario_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
